
###

GET http://localhost:8080/tag/list?videoId=8a8a838482103c2f0182103c6f0b0000

###

PUT http://localhost:8080/tag/adm/2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2NTgxMzAwMjIsImV4cCI6MTY1ODM0NjAyMiwiaXNzIjoiTWF6Z2kgcHJvZHVjdGlvbiIsImlkIjo1LCJyb2xlIjoiUk9MRV9BRE1JTiJ9.Qwr1YwDgtAxZ386VfIWSyJXbW73Us-UAJjZGqNJ_V7Y

{
  "name": "Dolzarb",
  "status": "ACTIVE"
}



###

DELETE http://localhost:8080/tag/adm/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2NTgxMzAwMjIsImV4cCI6MTY1ODM0NjAyMiwiaXNzIjoiTWF6Z2kgcHJvZHVjdGlvbiIsImlkIjo1LCJyb2xlIjoiUk9MRV9BRE1JTiJ9.Qwr1YwDgtAxZ386VfIWSyJXbW73Us-UAJjZGqNJ_V7Y
